-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE POLICY anon_insert_cases ON cases
 FOR INSERT
 WITH CHECK (true);

