-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

DROP POLICY IF EXISTS users_insert_own_cases ON cases; DROP POLICY IF EXISTS users_select_own_cases ON cases; DROP POLICY IF EXISTS users_update_own_cases ON cases; DROP POLICY IF EXISTS users_delete_own_cases ON cases;
